library(dplyr)
MC <- read.csv('MechaCar_mpg.csv')
lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD+mpg, data = MC)
summary(lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD, data = MC))
SC <- read.csv("Suspension_Coil.csv")
total_summary <- summarize(SC,mean(PSI),median(PSI),var(PSI),sd(PSI))
lot_summary <- group_by(SC, Manufacturing_Lot) %>% summarize(mean(PSI),median(PSI),var(PSI),sd(PSI))
t.test(SC$PSI, mu = 1500)
t.test(subset(SC$PSI,SC$Manufacturing_Lot == "Lot1"), mu = 1500)
t.test(subset(SC$PSI,SC$Manufacturing_Lot == "Lot2"), mu = 1500)
t.test(subset(SC$PSI,SC$Manufacturing_Lot == "Lot3"), mu = 1500)